import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  Permanent_Marker,
  Nothing_You_Could_Do,
  Balthazar,
  Poppins,
} from "next/font/google";
import "./globals.css";
import SocketInitializer from "./util/SocketInitializer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const permanentMarker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-permanent-marker",
});

const NothingYouCouldDo = Nothing_You_Could_Do({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-nothing-you-could-do",
});

const balthazarFont = Balthazar({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-balthazar",
});

const poppinsFont = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Remove useSocketStore and useEffect from here if not using "use client"
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${permanentMarker.variable} ${NothingYouCouldDo.variable}  ${balthazarFont.variable} ${poppinsFont.variable} `}
      >

        <SocketInitializer />
        {children}
      </body>
    </html>
  );
}